window.TYME_CITIES = [
  { id: 'utc', name: 'UTC', country: 'Worldwide', region: '', tz: 'UTC', aliases: 'gmt,zulu,universal' },
  { id: 'nyc', name: 'New York', country: 'United States', region: 'New York', tz: 'America/New_York', aliases: 'nyc,manhattan,brooklyn,edt,est' },
  { id: 'lax', name: 'Los Angeles', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'la,lax,hollywood,pdt,pst' },
  { id: 'chi', name: 'Chicago', country: 'United States', region: 'Illinois', tz: 'America/Chicago', aliases: 'chi,cdt,cst' },
  { id: 'den', name: 'Denver', country: 'United States', region: 'Colorado', tz: 'America/Denver', aliases: 'den,mdt,mst' },
  { id: 'sfo', name: 'San Francisco', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'sf,sfo,bay area' },
  { id: 'sea', name: 'Seattle', country: 'United States', region: 'Washington', tz: 'America/Los_Angeles', aliases: 'sea' },
  { id: 'bos', name: 'Boston', country: 'United States', region: 'Massachusetts', tz: 'America/New_York', aliases: 'bos' },
  { id: 'mia', name: 'Miami', country: 'United States', region: 'Florida', tz: 'America/New_York', aliases: 'mia' },
  { id: 'atl', name: 'Atlanta', country: 'United States', region: 'Georgia', tz: 'America/New_York', aliases: 'atl' },
  { id: 'dfw', name: 'Dallas', country: 'United States', region: 'Texas', tz: 'America/Chicago', aliases: 'dfw,dallas' },
  { id: 'hou', name: 'Houston', country: 'United States', region: 'Texas', tz: 'America/Chicago', aliases: 'hou' },
  { id: 'phx', name: 'Phoenix', country: 'United States', region: 'Arizona', tz: 'America/Phoenix', aliases: 'phx,az' },
  { id: 'wsh', name: 'Washington, D.C.', country: 'United States', region: 'District of Columbia', tz: 'America/New_York', aliases: 'dc,washington,d.c.' },
  { id: 'pdx', name: 'Portland', country: 'United States', region: 'Oregon', tz: 'America/Los_Angeles', aliases: 'pdx' },
  { id: 'las', name: 'Las Vegas', country: 'United States', region: 'Nevada', tz: 'America/Los_Angeles', aliases: 'vegas,las' },
  { id: 'hon', name: 'Honolulu', country: 'United States', region: 'Hawaii', tz: 'Pacific/Honolulu', aliases: 'hawaii,hnl' },
  { id: 'anc', name: 'Anchorage', country: 'United States', region: 'Alaska', tz: 'America/Anchorage', aliases: 'alaska' },
  { id: 'yyz', name: 'Toronto', country: 'Canada', region: 'Ontario', tz: 'America/Toronto', aliases: 'yyz' },
  { id: 'yvr', name: 'Vancouver', country: 'Canada', region: 'British Columbia', tz: 'America/Vancouver', aliases: 'yvr' },
  { id: 'yul', name: 'Montreal', country: 'Canada', region: 'Quebec', tz: 'America/Toronto', aliases: 'yul,montreal' },
  { id: 'yyc', name: 'Calgary', country: 'Canada', region: 'Alberta', tz: 'America/Edmonton', aliases: 'yyc' },
  { id: 'yeg', name: 'Edmonton', country: 'Canada', region: 'Alberta', tz: 'America/Edmonton', aliases: 'yeg' },
  { id: 'ywg', name: 'Winnipeg', country: 'Canada', region: 'Manitoba', tz: 'America/Winnipeg', aliases: 'ywg,manitoba' },
  { id: 'yow', name: 'Ottawa', country: 'Canada', region: 'Ontario', tz: 'America/Toronto', aliases: 'yow' },
  { id: 'yhz', name: 'Halifax', country: 'Canada', region: 'Nova Scotia', tz: 'America/Halifax', aliases: 'yhz' },
  { id: 'yqb', name: 'Quebec City', country: 'Canada', region: 'Quebec', tz: 'America/Toronto', aliases: 'yqb,quebec' },
  { id: 'yxe', name: 'Saskatoon', country: 'Canada', region: 'Saskatchewan', tz: 'America/Regina', aliases: 'yxe' },
  { id: 'yqr', name: 'Regina', country: 'Canada', region: 'Saskatchewan', tz: 'America/Regina', aliases: 'yqr' },
  { id: 'mex', name: 'Mexico City', country: 'Mexico', region: '', tz: 'America/Mexico_City', aliases: 'cdmx,df,mexico' },
  { id: 'gdl', name: 'Guadalajara', country: 'Mexico', region: 'Jalisco', tz: 'America/Mexico_City', aliases: 'gdl' },
  { id: 'mty', name: 'Monterrey', country: 'Mexico', region: 'Nuevo León', tz: 'America/Monterrey', aliases: 'mty' },
  { id: 'tij', name: 'Tijuana', country: 'Mexico', region: 'Baja California', tz: 'America/Tijuana', aliases: 'tij' },
  { id: 'sjo', name: 'San José', country: 'Costa Rica', region: '', tz: 'America/Costa_Rica', aliases: 'costa rica,sjo' },
  { id: 'pty', name: 'Panama City', country: 'Panama', region: '', tz: 'America/Panama', aliases: 'pty,panama' },
  { id: 'hav', name: 'Havana', country: 'Cuba', region: '', tz: 'America/Havana', aliases: 'havana,cuba' },
  { id: 'sdq', name: 'Santo Domingo', country: 'Dominican Republic', region: '', tz: 'America/Santo_Domingo', aliases: 'sdq' },
  { id: 'sju', name: 'San Juan', country: 'Puerto Rico', region: '', tz: 'America/Puerto_Rico', aliases: 'sju' },
  { id: 'kin', name: 'Kingston', country: 'Jamaica', region: '', tz: 'America/Jamaica', aliases: 'kin' },
  { id: 'pos', name: 'Port of Spain', country: 'Trinidad and Tobago', region: '', tz: 'America/Port_of_Spain', aliases: 'pos' },
  { id: 'msp', name: 'Minneapolis', country: 'United States', region: 'Minnesota', tz: 'America/Chicago', aliases: 'msp,twin cities' },
  { id: 'det', name: 'Detroit', country: 'United States', region: 'Michigan', tz: 'America/Detroit', aliases: 'det,dtw' },
  { id: 'phl', name: 'Philadelphia', country: 'United States', region: 'Pennsylvania', tz: 'America/New_York', aliases: 'phl,philly' },
  { id: 'san', name: 'San Diego', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'san' },
  { id: 'aus', name: 'Austin', country: 'United States', region: 'Texas', tz: 'America/Chicago', aliases: 'aus' },
  { id: 'slc', name: 'Salt Lake City', country: 'United States', region: 'Utah', tz: 'America/Denver', aliases: 'slc' },
  { id: 'bna', name: 'Nashville', country: 'United States', region: 'Tennessee', tz: 'America/Chicago', aliases: 'bna' },
  { id: 'clt', name: 'Charlotte', country: 'United States', region: 'North Carolina', tz: 'America/New_York', aliases: 'clt' },
  { id: 'mci', name: 'Kansas City', country: 'United States', region: 'Missouri', tz: 'America/Chicago', aliases: 'mci' },
  { id: 'stl', name: 'St. Louis', country: 'United States', region: 'Missouri', tz: 'America/Chicago', aliases: 'stl' },
  { id: 'pit', name: 'Pittsburgh', country: 'United States', region: 'Pennsylvania', tz: 'America/New_York', aliases: 'pit' },
  { id: 'cle', name: 'Cleveland', country: 'United States', region: 'Ohio', tz: 'America/New_York', aliases: 'cle' },
  { id: 'ind', name: 'Indianapolis', country: 'United States', region: 'Indiana', tz: 'America/Indiana/Indianapolis', aliases: 'ind' },
  { id: 'cmh', name: 'Columbus', country: 'United States', region: 'Ohio', tz: 'America/New_York', aliases: 'cmh' },
  { id: 'rdu', name: 'Raleigh', country: 'United States', region: 'North Carolina', tz: 'America/New_York', aliases: 'rdu' },
  { id: 'mke', name: 'Milwaukee', country: 'United States', region: 'Wisconsin', tz: 'America/Chicago', aliases: 'mke' },
  { id: 'orl', name: 'Orlando', country: 'United States', region: 'Florida', tz: 'America/New_York', aliases: 'mco,orlando' },
  { id: 'tpa', name: 'Tampa', country: 'United States', region: 'Florida', tz: 'America/New_York', aliases: 'tpa' },
  { id: 'sat', name: 'San Antonio', country: 'United States', region: 'Texas', tz: 'America/Chicago', aliases: 'sat' },
  { id: 'abq', name: 'Albuquerque', country: 'United States', region: 'New Mexico', tz: 'America/Denver', aliases: 'abq' },
  { id: 'boi', name: 'Boise', country: 'United States', region: 'Idaho', tz: 'America/Boise', aliases: 'boi' },
  { id: 'rno', name: 'Reno', country: 'United States', region: 'Nevada', tz: 'America/Los_Angeles', aliases: 'rno' },
  { id: 'sao', name: 'São Paulo', country: 'Brazil', region: 'São Paulo', tz: 'America/Sao_Paulo', aliases: 'sao,sp,brasil,brazil' },
  { id: 'rio', name: 'Rio de Janeiro', country: 'Brazil', region: 'Rio de Janeiro', tz: 'America/Sao_Paulo', aliases: 'rio,rj,brasil' },
  { id: 'bsb', name: 'Brasília', country: 'Brazil', region: 'Distrito Federal', tz: 'America/Sao_Paulo', aliases: 'bsb,brasilia,df' },
  { id: 'bhz', name: 'Belo Horizonte', country: 'Brazil', region: 'Minas Gerais', tz: 'America/Sao_Paulo', aliases: 'bh,bhz' },
  { id: 'cur', name: 'Curitiba', country: 'Brazil', region: 'Paraná', tz: 'America/Sao_Paulo', aliases: 'cwb,curitiba' },
  { id: 'poa', name: 'Porto Alegre', country: 'Brazil', region: 'Rio Grande do Sul', tz: 'America/Sao_Paulo', aliases: 'poa' },
  { id: 'ssa', name: 'Salvador', country: 'Brazil', region: 'Bahia', tz: 'America/Bahia', aliases: 'ssa,bahia' },
  { id: 'rec', name: 'Recife', country: 'Brazil', region: 'Pernambuco', tz: 'America/Recife', aliases: 'rec' },
  { id: 'for', name: 'Fortaleza', country: 'Brazil', region: 'Ceará', tz: 'America/Fortaleza', aliases: 'for' },
  { id: 'mao', name: 'Manaus', country: 'Brazil', region: 'Amazonas', tz: 'America/Manaus', aliases: 'mao,amazonas' },
  { id: 'bel', name: 'Belém', country: 'Brazil', region: 'Pará', tz: 'America/Belem', aliases: 'bel,belem,para' },
  { id: 'fln', name: 'Florianópolis', country: 'Brazil', region: 'Santa Catarina', tz: 'America/Sao_Paulo', aliases: 'fln,floripa' },
  { id: 'gyn', name: 'Goiânia', country: 'Brazil', region: 'Goiás', tz: 'America/Sao_Paulo', aliases: 'gyn,goiania' },
  { id: 'vix', name: 'Vitória', country: 'Brazil', region: 'Espírito Santo', tz: 'America/Sao_Paulo', aliases: 'vix,vitoria' },
  { id: 'cgb', name: 'Cuiabá', country: 'Brazil', region: 'Mato Grosso', tz: 'America/Cuiaba', aliases: 'cgb,cuiaba' },
  { id: 'cgr', name: 'Campo Grande', country: 'Brazil', region: 'Mato Grosso do Sul', tz: 'America/Campo_Grande', aliases: 'cgr' },
  { id: 'nat', name: 'Natal', country: 'Brazil', region: 'Rio Grande do Norte', tz: 'America/Fortaleza', aliases: 'nat' },
  { id: 'slz', name: 'São Luís', country: 'Brazil', region: 'Maranhão', tz: 'America/Fortaleza', aliases: 'slz,sao luis' },
  { id: 'the', name: 'Teresina', country: 'Brazil', region: 'Piauí', tz: 'America/Fortaleza', aliases: 'the' },
  { id: 'jdo', name: 'João Pessoa', country: 'Brazil', region: 'Paraíba', tz: 'America/Fortaleza', aliases: 'jpa,joao pessoa' },
  { id: 'mcp', name: 'Macapá', country: 'Brazil', region: 'Amapá', tz: 'America/Belem', aliases: 'mcp,macapa' },
  { id: 'pvh', name: 'Porto Velho', country: 'Brazil', region: 'Rondônia', tz: 'America/Porto_Velho', aliases: 'pvh' },
  { id: 'rbr', name: 'Rio Branco', country: 'Brazil', region: 'Acre', tz: 'America/Rio_Branco', aliases: 'rbr,acre' },
  { id: 'bue', name: 'Buenos Aires', country: 'Argentina', region: '', tz: 'America/Argentina/Buenos_Aires', aliases: 'eze,baires' },
  { id: 'cor', name: 'Córdoba', country: 'Argentina', region: '', tz: 'America/Argentina/Cordoba', aliases: 'cor,cordoba' },
  { id: 'mdz', name: 'Mendoza', country: 'Argentina', region: '', tz: 'America/Argentina/Mendoza', aliases: 'mdz' },
  { id: 'scl', name: 'Santiago', country: 'Chile', region: '', tz: 'America/Santiago', aliases: 'scl' },
  { id: 'lim', name: 'Lima', country: 'Peru', region: '', tz: 'America/Lima', aliases: 'lim' },
  { id: 'bog', name: 'Bogotá', country: 'Colombia', region: '', tz: 'America/Bogota', aliases: 'bog,bogota' },
  { id: 'mde', name: 'Medellín', country: 'Colombia', region: '', tz: 'America/Bogota', aliases: 'mde,medellin' },
  { id: 'clo', name: 'Cali', country: 'Colombia', region: '', tz: 'America/Bogota', aliases: 'clo' },
  { id: 'uio', name: 'Quito', country: 'Ecuador', region: '', tz: 'America/Guayaquil', aliases: 'uio' },
  { id: 'gye', name: 'Guayaquil', country: 'Ecuador', region: '', tz: 'America/Guayaquil', aliases: 'gye' },
  { id: 'ccs', name: 'Caracas', country: 'Venezuela', region: '', tz: 'America/Caracas', aliases: 'ccs' },
  { id: 'mvd', name: 'Montevideo', country: 'Uruguay', region: '', tz: 'America/Montevideo', aliases: 'mvd' },
  { id: 'asuncion', name: 'Asunción', country: 'Paraguay', region: '', tz: 'America/Asuncion', aliases: 'asuncion,asu' },
  { id: 'lpb', name: 'La Paz', country: 'Bolivia', region: '', tz: 'America/La_Paz', aliases: 'lpb' },
  { id: 'sre', name: 'Sucre', country: 'Bolivia', region: '', tz: 'America/La_Paz', aliases: 'sre' },
  { id: 'geo', name: 'Georgetown', country: 'Guyana', region: '', tz: 'America/Guyana', aliases: 'geo' },
  { id: 'pbm', name: 'Paramaribo', country: 'Suriname', region: '', tz: 'America/Paramaribo', aliases: 'pbm' },
  { id: 'lon', name: 'London', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'lon,uk,britain,bst,gmt' },
  { id: 'man', name: 'Manchester', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'man' },
  { id: 'edi', name: 'Edinburgh', country: 'United Kingdom', region: 'Scotland', tz: 'Europe/London', aliases: 'edi' },
  { id: 'dub', name: 'Dublin', country: 'Ireland', region: '', tz: 'Europe/Dublin', aliases: 'dub' },
  { id: 'lis', name: 'Lisbon', country: 'Portugal', region: '', tz: 'Europe/Lisbon', aliases: 'lis,lisboa' },
  { id: 'opo', name: 'Porto', country: 'Portugal', region: '', tz: 'Europe/Lisbon', aliases: 'opo,oporto' },
  { id: 'mad', name: 'Madrid', country: 'Spain', region: '', tz: 'Europe/Madrid', aliases: 'mad' },
  { id: 'bcn', name: 'Barcelona', country: 'Spain', region: 'Catalonia', tz: 'Europe/Madrid', aliases: 'bcn' },
  { id: 'par', name: 'Paris', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'par,cdt,cest' },
  { id: 'ams', name: 'Amsterdam', country: 'Netherlands', region: '', tz: 'Europe/Amsterdam', aliases: 'ams' },
  { id: 'bru', name: 'Brussels', country: 'Belgium', region: '', tz: 'Europe/Brussels', aliases: 'bru' },
  { id: 'ber', name: 'Berlin', country: 'Germany', region: '', tz: 'Europe/Berlin', aliases: 'ber' },
  { id: 'muc', name: 'Munich', country: 'Germany', region: 'Bavaria', tz: 'Europe/Berlin', aliases: 'muc,munchen' },
  { id: 'fra', name: 'Frankfurt', country: 'Germany', region: '', tz: 'Europe/Berlin', aliases: 'fra' },
  { id: 'ham', name: 'Hamburg', country: 'Germany', region: '', tz: 'Europe/Berlin', aliases: 'ham' },
  { id: 'zur', name: 'Zurich', country: 'Switzerland', region: '', tz: 'Europe/Zurich', aliases: 'zur,zuerich' },
  { id: 'gva', name: 'Geneva', country: 'Switzerland', region: '', tz: 'Europe/Zurich', aliases: 'gva' },
  { id: 'vie', name: 'Vienna', country: 'Austria', region: '', tz: 'Europe/Vienna', aliases: 'vie' },
  { id: 'rom', name: 'Rome', country: 'Italy', region: '', tz: 'Europe/Rome', aliases: 'rom,roma' },
  { id: 'mil', name: 'Milan', country: 'Italy', region: '', tz: 'Europe/Rome', aliases: 'mil,milano' },
  { id: 'sto', name: 'Stockholm', country: 'Sweden', region: '', tz: 'Europe/Stockholm', aliases: 'sto,arn' },
  { id: 'osl', name: 'Oslo', country: 'Norway', region: '', tz: 'Europe/Oslo', aliases: 'osl' },
  { id: 'cph', name: 'Copenhagen', country: 'Denmark', region: '', tz: 'Europe/Copenhagen', aliases: 'cph' },
  { id: 'hel', name: 'Helsinki', country: 'Finland', region: '', tz: 'Europe/Helsinki', aliases: 'hel' },
  { id: 'waw', name: 'Warsaw', country: 'Poland', region: '', tz: 'Europe/Warsaw', aliases: 'waw' },
  { id: 'prg', name: 'Prague', country: 'Czechia', region: '', tz: 'Europe/Prague', aliases: 'prg' },
  { id: 'bud', name: 'Budapest', country: 'Hungary', region: '', tz: 'Europe/Budapest', aliases: 'bud' },
  { id: 'ath', name: 'Athens', country: 'Greece', region: '', tz: 'Europe/Athens', aliases: 'ath' },
  { id: 'ist', name: 'Istanbul', country: 'Türkiye', region: '', tz: 'Europe/Istanbul', aliases: 'ist,turkey' },
  { id: 'msk', name: 'Moscow', country: 'Russia', region: '', tz: 'Europe/Moscow', aliases: 'msk,svo' },
  { id: 'kiev', name: 'Kyiv', country: 'Ukraine', region: '', tz: 'Europe/Kyiv', aliases: 'kiev,kyiv,iev' },
  { id: 'buc', name: 'Bucharest', country: 'Romania', region: '', tz: 'Europe/Bucharest', aliases: 'otp' },
  { id: 'sof', name: 'Sofia', country: 'Bulgaria', region: '', tz: 'Europe/Sofia', aliases: 'sof' },
  { id: 'beg', name: 'Belgrade', country: 'Serbia', region: '', tz: 'Europe/Belgrade', aliases: 'beg' },
  { id: 'zag', name: 'Zagreb', country: 'Croatia', region: '', tz: 'Europe/Zagreb', aliases: 'zag' },
  { id: 'rix', name: 'Riga', country: 'Latvia', region: '', tz: 'Europe/Riga', aliases: 'rix' },
  { id: 'tal', name: 'Tallinn', country: 'Estonia', region: '', tz: 'Europe/Tallinn', aliases: 'tll' },
  { id: 'vno', name: 'Vilnius', country: 'Lithuania', region: '', tz: 'Europe/Vilnius', aliases: 'vno' },
  { id: 'lux', name: 'Luxembourg', country: 'Luxembourg', region: '', tz: 'Europe/Luxembourg', aliases: 'lux' },
  { id: 'rey', name: 'Reykjavík', country: 'Iceland', region: '', tz: 'Atlantic/Reykjavik', aliases: 'rey,rekjavik,iceland' },
  { id: 'gla', name: 'Glasgow', country: 'United Kingdom', region: 'Scotland', tz: 'Europe/London', aliases: 'gla' },
  { id: 'bhx', name: 'Birmingham', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'bhx' },
  { id: 'brs', name: 'Bristol', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'brs' },
  { id: 'vlc', name: 'Valencia', country: 'Spain', region: '', tz: 'Europe/Madrid', aliases: 'vlc' },
  { id: 'svq', name: 'Seville', country: 'Spain', region: '', tz: 'Europe/Madrid', aliases: 'svq,sevilla' },
  { id: 'lyo', name: 'Lyon', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'lys,lyon' },
  { id: 'mrs', name: 'Marseille', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'mrs' },
  { id: 'cgn', name: 'Cologne', country: 'Germany', region: '', tz: 'Europe/Berlin', aliases: 'cgn,koln,koeln' },
  { id: 'str', name: 'Stuttgart', country: 'Germany', region: '', tz: 'Europe/Berlin', aliases: 'str' },
  { id: 'dus', name: 'Düsseldorf', country: 'Germany', region: '', tz: 'Europe/Berlin', aliases: 'dus,dusseldorf' },
  { id: 'nap', name: 'Naples', country: 'Italy', region: '', tz: 'Europe/Rome', aliases: 'nap,napoli' },
  { id: 'trn', name: 'Turin', country: 'Italy', region: '', tz: 'Europe/Rome', aliases: 'trn,torino' },
  { id: 'flr', name: 'Florence', country: 'Italy', region: '', tz: 'Europe/Rome', aliases: 'flr,firenze' },
  { id: 'bsl', name: 'Basel', country: 'Switzerland', region: '', tz: 'Europe/Zurich', aliases: 'bsl' },
  { id: 'brn', name: 'Bern', country: 'Switzerland', region: '', tz: 'Europe/Zurich', aliases: 'brn' },
  { id: 'goth', name: 'Gothenburg', country: 'Sweden', region: '', tz: 'Europe/Stockholm', aliases: 'got,gothenburg' },
  { id: 'krk', name: 'Kraków', country: 'Poland', region: '', tz: 'Europe/Warsaw', aliases: 'krk,krakow' },
  { id: 'gdn', name: 'Gdańsk', country: 'Poland', region: '', tz: 'Europe/Warsaw', aliases: 'gdn,gdansk' },
  { id: 'lju', name: 'Ljubljana', country: 'Slovenia', region: '', tz: 'Europe/Ljubljana', aliases: 'lju' },
  { id: 'skp', name: 'Skopje', country: 'North Macedonia', region: '', tz: 'Europe/Skopje', aliases: 'skp' },
  { id: 'tir', name: 'Tirana', country: 'Albania', region: '', tz: 'Europe/Tirane', aliases: 'tia,tirana' },
  { id: 'nic', name: 'Nicosia', country: 'Cyprus', region: '', tz: 'Asia/Nicosia', aliases: 'nic' },
  { id: 'mlt', name: 'Valletta', country: 'Malta', region: '', tz: 'Europe/Malta', aliases: 'mla,valletta' },
  { id: 'cai', name: 'Cairo', country: 'Egypt', region: '', tz: 'Africa/Cairo', aliases: 'cai' },
  { id: 'jnb', name: 'Johannesburg', country: 'South Africa', region: '', tz: 'Africa/Johannesburg', aliases: 'jnb,joburg' },
  { id: 'cpt', name: 'Cape Town', country: 'South Africa', region: '', tz: 'Africa/Johannesburg', aliases: 'cpt' },
  { id: 'nbo', name: 'Nairobi', country: 'Kenya', region: '', tz: 'Africa/Nairobi', aliases: 'nbo' },
  { id: 'lag', name: 'Lagos', country: 'Nigeria', region: '', tz: 'Africa/Lagos', aliases: 'los' },
  { id: 'acc', name: 'Accra', country: 'Ghana', region: '', tz: 'Africa/Accra', aliases: 'acc' },
  { id: 'cas', name: 'Casablanca', country: 'Morocco', region: '', tz: 'Africa/Casablanca', aliases: 'cmn' },
  { id: 'tun', name: 'Tunis', country: 'Tunisia', region: '', tz: 'Africa/Tunis', aliases: 'tun' },
  { id: 'alg', name: 'Algiers', country: 'Algeria', region: '', tz: 'Africa/Algiers', aliases: 'alg' },
  { id: 'add', name: 'Addis Ababa', country: 'Ethiopia', region: '', tz: 'Africa/Addis_Ababa', aliases: 'add' },
  { id: 'dar', name: 'Dar es Salaam', country: 'Tanzania', region: '', tz: 'Africa/Dar_es_Salaam', aliases: 'dar' },
  { id: 'kla', name: 'Kampala', country: 'Uganda', region: '', tz: 'Africa/Kampala', aliases: 'kla' },
  { id: 'dkr', name: 'Dakar', country: 'Senegal', region: '', tz: 'Africa/Dakar', aliases: 'dkr' },
  { id: 'mpm', name: 'Maputo', country: 'Mozambique', region: '', tz: 'Africa/Maputo', aliases: 'mpm' },
  { id: 'wdh', name: 'Windhoek', country: 'Namibia', region: '', tz: 'Africa/Windhoek', aliases: 'wdh' },
  { id: 'lun', name: 'Lusaka', country: 'Zambia', region: '', tz: 'Africa/Lusaka', aliases: 'lun' },
  { id: 'hre', name: 'Harare', country: 'Zimbabwe', region: '', tz: 'Africa/Harare', aliases: 'hre' },
  { id: 'abj', name: 'Abidjan', country: 'Côte d\'Ivoire', region: '', tz: 'Africa/Abidjan', aliases: 'abj,ivory coast' },
  { id: 'lad', name: 'Luanda', country: 'Angola', region: '', tz: 'Africa/Luanda', aliases: 'lad,luanda' },
  { id: 'dxb', name: 'Dubai', country: 'United Arab Emirates', region: '', tz: 'Asia/Dubai', aliases: 'dxb,uae' },
  { id: 'auh', name: 'Abu Dhabi', country: 'United Arab Emirates', region: '', tz: 'Asia/Dubai', aliases: 'auh' },
  { id: 'ruh', name: 'Riyadh', country: 'Saudi Arabia', region: '', tz: 'Asia/Riyadh', aliases: 'ruh' },
  { id: 'jed', name: 'Jeddah', country: 'Saudi Arabia', region: '', tz: 'Asia/Riyadh', aliases: 'jed' },
  { id: 'doh', name: 'Doha', country: 'Qatar', region: '', tz: 'Asia/Qatar', aliases: 'doh' },
  { id: 'kwi', name: 'Kuwait City', country: 'Kuwait', region: '', tz: 'Asia/Kuwait', aliases: 'kwi' },
  { id: 'bah', name: 'Manama', country: 'Bahrain', region: '', tz: 'Asia/Bahrain', aliases: 'bah' },
  { id: 'mct', name: 'Muscat', country: 'Oman', region: '', tz: 'Asia/Muscat', aliases: 'mct' },
  { id: 'tlv', name: 'Tel Aviv', country: 'Israel', region: '', tz: 'Asia/Jerusalem', aliases: 'tlv,jerusalem' },
  { id: 'amm', name: 'Amman', country: 'Jordan', region: '', tz: 'Asia/Amman', aliases: 'amm' },
  { id: 'bey', name: 'Beirut', country: 'Lebanon', region: '', tz: 'Asia/Beirut', aliases: 'bey' },
  { id: 'thr', name: 'Tehran', country: 'Iran', region: '', tz: 'Asia/Tehran', aliases: 'thr,ika' },
  { id: 'bak', name: 'Baku', country: 'Azerbaijan', region: '', tz: 'Asia/Baku', aliases: 'bak' },
  { id: 'tbs', name: 'Tbilisi', country: 'Georgia', region: '', tz: 'Asia/Tbilisi', aliases: 'tbs' },
  { id: 'evn', name: 'Yerevan', country: 'Armenia', region: '', tz: 'Asia/Yerevan', aliases: 'evn' },
  { id: 'tas', name: 'Tashkent', country: 'Uzbekistan', region: '', tz: 'Asia/Tashkent', aliases: 'tas' },
  { id: 'ala', name: 'Almaty', country: 'Kazakhstan', region: '', tz: 'Asia/Almaty', aliases: 'ala' },
  { id: 'nqz', name: 'Astana', country: 'Kazakhstan', region: '', tz: 'Asia/Almaty', aliases: 'nqz,nur-sultan' },
  { id: 'del', name: 'New Delhi', country: 'India', region: '', tz: 'Asia/Kolkata', aliases: 'del,delhi,ist' },
  { id: 'bom', name: 'Mumbai', country: 'India', region: 'Maharashtra', tz: 'Asia/Kolkata', aliases: 'bom,bombay' },
  { id: 'blr', name: 'Bengaluru', country: 'India', region: 'Karnataka', tz: 'Asia/Kolkata', aliases: 'blr,bangalore' },
  { id: 'hyd', name: 'Hyderabad', country: 'India', region: 'Telangana', tz: 'Asia/Kolkata', aliases: 'hyd' },
  { id: 'ccu', name: 'Kolkata', country: 'India', region: 'West Bengal', tz: 'Asia/Kolkata', aliases: 'ccu,calcutta' },
  { id: 'chn', name: 'Chennai', country: 'India', region: 'Tamil Nadu', tz: 'Asia/Kolkata', aliases: 'maa,madras' },
  { id: 'pnq', name: 'Pune', country: 'India', region: 'Maharashtra', tz: 'Asia/Kolkata', aliases: 'pnq' },
  { id: 'jai', name: 'Jaipur', country: 'India', region: 'Rajasthan', tz: 'Asia/Kolkata', aliases: 'jai' },
  { id: 'amd', name: 'Ahmedabad', country: 'India', region: 'Gujarat', tz: 'Asia/Kolkata', aliases: 'amd' },
  { id: 'khi', name: 'Karachi', country: 'Pakistan', region: '', tz: 'Asia/Karachi', aliases: 'khi' },
  { id: 'isb', name: 'Islamabad', country: 'Pakistan', region: '', tz: 'Asia/Karachi', aliases: 'isb' },
  { id: 'lhe', name: 'Lahore', country: 'Pakistan', region: '', tz: 'Asia/Karachi', aliases: 'lhe' },
  { id: 'dac', name: 'Dhaka', country: 'Bangladesh', region: '', tz: 'Asia/Dhaka', aliases: 'dac' },
  { id: 'cmb', name: 'Colombo', country: 'Sri Lanka', region: '', tz: 'Asia/Colombo', aliases: 'cmb' },
  { id: 'ktm', name: 'Kathmandu', country: 'Nepal', region: '', tz: 'Asia/Kathmandu', aliases: 'ktm' },
  { id: 'bkk', name: 'Bangkok', country: 'Thailand', region: '', tz: 'Asia/Bangkok', aliases: 'bkk' },
  { id: 'sin', name: 'Singapore', country: 'Singapore', region: '', tz: 'Asia/Singapore', aliases: 'sin,sg' },
  { id: 'kul', name: 'Kuala Lumpur', country: 'Malaysia', region: '', tz: 'Asia/Kuala_Lumpur', aliases: 'kul' },
  { id: 'jkt', name: 'Jakarta', country: 'Indonesia', region: '', tz: 'Asia/Jakarta', aliases: 'jkt,cgk' },
  { id: 'dps', name: 'Denpasar', country: 'Indonesia', region: 'Bali', tz: 'Asia/Makassar', aliases: 'dps,bali' },
  { id: 'mnl', name: 'Manila', country: 'Philippines', region: '', tz: 'Asia/Manila', aliases: 'mnl' },
  { id: 'hcm', name: 'Ho Chi Minh City', country: 'Vietnam', region: '', tz: 'Asia/Ho_Chi_Minh', aliases: 'sgn,saigon,hcmc' },
  { id: 'han', name: 'Hanoi', country: 'Vietnam', region: '', tz: 'Asia/Bangkok', aliases: 'han' },
  { id: 'pnh', name: 'Phnom Penh', country: 'Cambodia', region: '', tz: 'Asia/Phnom_Penh', aliases: 'pnh' },
  { id: 'rgm', name: 'Yangon', country: 'Myanmar', region: '', tz: 'Asia/Yangon', aliases: 'rgm,rangoon' },
  { id: 'hkg', name: 'Hong Kong', country: 'Hong Kong', region: '', tz: 'Asia/Hong_Kong', aliases: 'hkg,hk' },
  { id: 'tpe', name: 'Taipei', country: 'Taiwan', region: '', tz: 'Asia/Taipei', aliases: 'tpe' },
  { id: 'sel', name: 'Seoul', country: 'South Korea', region: '', tz: 'Asia/Seoul', aliases: 'sel,icn' },
  { id: 'pus', name: 'Busan', country: 'South Korea', region: '', tz: 'Asia/Seoul', aliases: 'pus,pusan' },
  { id: 'tyo', name: 'Tokyo', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'tyo,nrt,hnd,jst' },
  { id: 'osa', name: 'Osaka', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'osa,kix' },
  { id: 'ngo', name: 'Nagoya', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'ngo' },
  { id: 'sap', name: 'Sapporo', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'sap' },
  { id: 'sha', name: 'Shanghai', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'sha,pvg' },
  { id: 'pek', name: 'Beijing', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'pek,peking' },
  { id: 'can', name: 'Guangzhou', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'can' },
  { id: 'szx', name: 'Shenzhen', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'szx' },
  { id: 'ctu', name: 'Chengdu', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'ctu' },
  { id: 'ckg', name: 'Chongqing', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'ckg' },
  { id: 'wuh', name: 'Wuhan', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'wuh' },
  { id: 'uln', name: 'Ulaanbaatar', country: 'Mongolia', region: '', tz: 'Asia/Ulaanbaatar', aliases: 'uln' },
  { id: 'syd', name: 'Sydney', country: 'Australia', region: 'New South Wales', tz: 'Australia/Sydney', aliases: 'syd,aedt' },
  { id: 'mel', name: 'Melbourne', country: 'Australia', region: 'Victoria', tz: 'Australia/Melbourne', aliases: 'mel' },
  { id: 'bne', name: 'Brisbane', country: 'Australia', region: 'Queensland', tz: 'Australia/Brisbane', aliases: 'bne' },
  { id: 'per', name: 'Perth', country: 'Australia', region: 'Western Australia', tz: 'Australia/Perth', aliases: 'per' },
  { id: 'adl', name: 'Adelaide', country: 'Australia', region: 'South Australia', tz: 'Australia/Adelaide', aliases: 'adl' },
  { id: 'hba', name: 'Hobart', country: 'Australia', region: 'Tasmania', tz: 'Australia/Hobart', aliases: 'hba' },
  { id: 'cbr', name: 'Canberra', country: 'Australia', region: 'Australian Capital Territory', tz: 'Australia/Sydney', aliases: 'cbr' },
  { id: 'drw', name: 'Darwin', country: 'Australia', region: 'Northern Territory', tz: 'Australia/Darwin', aliases: 'drw' },
  { id: 'akl', name: 'Auckland', country: 'New Zealand', region: '', tz: 'Pacific/Auckland', aliases: 'akl,nz' },
  { id: 'wlg', name: 'Wellington', country: 'New Zealand', region: '', tz: 'Pacific/Auckland', aliases: 'wlg' },
  { id: 'chc', name: 'Christchurch', country: 'New Zealand', region: '', tz: 'Pacific/Auckland', aliases: 'chc' },
  { id: 'fij', name: 'Suva', country: 'Fiji', region: '', tz: 'Pacific/Fiji', aliases: 'suv,fiji' },
  { id: 'gum', name: 'Hagåtña', country: 'Guam', region: '', tz: 'Pacific/Guam', aliases: 'gum,guam,hagatna' },
  { id: 'ppt', name: 'Papeete', country: 'French Polynesia', region: 'Tahiti', tz: 'Pacific/Tahiti', aliases: 'ppt,tahiti' },
  { id: 'nou', name: 'Nouméa', country: 'New Caledonia', region: '', tz: 'Pacific/Noumea', aliases: 'nou,noumea' },
  { id: 'apw', name: 'Apia', country: 'Samoa', region: '', tz: 'Pacific/Apia', aliases: 'apw' },
  { id: 'yyt', name: 'St. John\'s', country: 'Canada', region: 'Newfoundland and Labrador', tz: 'America/St_Johns', aliases: 'yyt,newfoundland,st johns' },
  { id: 'yxy', name: 'Whitehorse', country: 'Canada', region: 'Yukon', tz: 'America/Whitehorse', aliases: 'yxy,yukon' },
  { id: 'yzf', name: 'Yellowknife', country: 'Canada', region: 'Northwest Territories', tz: 'America/Yellowknife', aliases: 'yzf' },
  { id: 'yfb', name: 'Iqaluit', country: 'Canada', region: 'Nunavut', tz: 'America/Iqaluit', aliases: 'yfb' },
  { id: 'yqm', name: 'Moncton', country: 'Canada', region: 'New Brunswick', tz: 'America/Moncton', aliases: 'yqm' },
  { id: 'yyg', name: 'Charlottetown', country: 'Canada', region: 'Prince Edward Island', tz: 'America/Halifax', aliases: 'yyg' },
  { id: 'yjs', name: 'Victoria', country: 'Canada', region: 'British Columbia', tz: 'America/Vancouver', aliases: 'yyj,victoria bc' },
  { id: 'yxu', name: 'London', country: 'Canada', region: 'Ontario', tz: 'America/Toronto', aliases: 'yxu,london ontario' },
  { id: 'yhm', name: 'Hamilton', country: 'Canada', region: 'Ontario', tz: 'America/Toronto', aliases: 'yhm' },
  { id: 'yxh', name: 'Medicine Hat', country: 'Canada', region: 'Alberta', tz: 'America/Edmonton', aliases: 'yxh' },
  { id: 'buf', name: 'Buffalo', country: 'United States', region: 'New York', tz: 'America/New_York', aliases: 'buf' },
  { id: 'roc', name: 'Rochester', country: 'United States', region: 'New York', tz: 'America/New_York', aliases: 'roc' },
  { id: 'alb', name: 'Albany', country: 'United States', region: 'New York', tz: 'America/New_York', aliases: 'alb' },
  { id: 'bdl', name: 'Hartford', country: 'United States', region: 'Connecticut', tz: 'America/New_York', aliases: 'bdl' },
  { id: 'pvd', name: 'Providence', country: 'United States', region: 'Rhode Island', tz: 'America/New_York', aliases: 'pvd' },
  { id: 'pwm', name: 'Portland', country: 'United States', region: 'Maine', tz: 'America/New_York', aliases: 'pwm,portland maine' },
  { id: 'btv', name: 'Burlington', country: 'United States', region: 'Vermont', tz: 'America/New_York', aliases: 'btv' },
  { id: 'ric', name: 'Richmond', country: 'United States', region: 'Virginia', tz: 'America/New_York', aliases: 'ric' },
  { id: 'orf', name: 'Norfolk', country: 'United States', region: 'Virginia', tz: 'America/New_York', aliases: 'orf' },
  { id: 'chs', name: 'Charleston', country: 'United States', region: 'South Carolina', tz: 'America/New_York', aliases: 'chs' },
  { id: 'sav', name: 'Savannah', country: 'United States', region: 'Georgia', tz: 'America/New_York', aliases: 'sav' },
  { id: 'jax', name: 'Jacksonville', country: 'United States', region: 'Florida', tz: 'America/New_York', aliases: 'jax' },
  { id: 'fll', name: 'Fort Lauderdale', country: 'United States', region: 'Florida', tz: 'America/New_York', aliases: 'fll' },
  { id: 'mem', name: 'Memphis', country: 'United States', region: 'Tennessee', tz: 'America/Chicago', aliases: 'mem' },
  { id: 'lit', name: 'Little Rock', country: 'United States', region: 'Arkansas', tz: 'America/Chicago', aliases: 'lit' },
  { id: 'okc', name: 'Oklahoma City', country: 'United States', region: 'Oklahoma', tz: 'America/Chicago', aliases: 'okc' },
  { id: 'tul', name: 'Tulsa', country: 'United States', region: 'Oklahoma', tz: 'America/Chicago', aliases: 'tul' },
  { id: 'oma', name: 'Omaha', country: 'United States', region: 'Nebraska', tz: 'America/Chicago', aliases: 'oma' },
  { id: 'dsm', name: 'Des Moines', country: 'United States', region: 'Iowa', tz: 'America/Chicago', aliases: 'dsm' },
  { id: 'msy', name: 'New Orleans', country: 'United States', region: 'Louisiana', tz: 'America/Chicago', aliases: 'msy,nola' },
  { id: 'bhm', name: 'Birmingham', country: 'United States', region: 'Alabama', tz: 'America/Chicago', aliases: 'bhm' },
  { id: 'hsv', name: 'Huntsville', country: 'United States', region: 'Alabama', tz: 'America/Chicago', aliases: 'hsv' },
  { id: 'elp', name: 'El Paso', country: 'United States', region: 'Texas', tz: 'America/Denver', aliases: 'elp' },
  { id: 'tus', name: 'Tucson', country: 'United States', region: 'Arizona', tz: 'America/Phoenix', aliases: 'tus' },
  { id: 'sjc', name: 'San Jose', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'sjc' },
  { id: 'sac', name: 'Sacramento', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'sac' },
  { id: 'oak', name: 'Oakland', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'oak' },
  { id: 'smf', name: 'Fresno', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'fat,fresno' },
  { id: 'sna', name: 'Santa Ana', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'sna,orange county' },
  { id: 'ont', name: 'Ontario', country: 'United States', region: 'California', tz: 'America/Los_Angeles', aliases: 'ont' },
  { id: 'geg', name: 'Spokane', country: 'United States', region: 'Washington', tz: 'America/Los_Angeles', aliases: 'geg' },
  { id: 'fai', name: 'Fairbanks', country: 'United States', region: 'Alaska', tz: 'America/Anchorage', aliases: 'fai' },
  { id: 'adk', name: 'Adak', country: 'United States', region: 'Alaska', tz: 'America/Adak', aliases: 'adk' },
  { id: 'jnu', name: 'Juneau', country: 'United States', region: 'Alaska', tz: 'America/Juneau', aliases: 'jnu' },
  { id: 'cun', name: 'Cancún', country: 'Mexico', region: 'Quintana Roo', tz: 'America/Cancun', aliases: 'cun,cancun' },
  { id: 'mid', name: 'Mérida', country: 'Mexico', region: 'Yucatán', tz: 'America/Merida', aliases: 'mid,merida' },
  { id: 'pvr', name: 'Puerto Vallarta', country: 'Mexico', region: 'Jalisco', tz: 'America/Mexico_City', aliases: 'pvr' },
  { id: 'hmo', name: 'Hermosillo', country: 'Mexico', region: 'Sonora', tz: 'America/Hermosillo', aliases: 'hmo' },
  { id: 'cul', name: 'Culiacán', country: 'Mexico', region: 'Sinaloa', tz: 'America/Mazatlan', aliases: 'cul,culiacan' },
  { id: 'bjx', name: 'León', country: 'Mexico', region: 'Guanajuato', tz: 'America/Mexico_City', aliases: 'bjx,leon' },
  { id: 'pbc', name: 'Puebla', country: 'Mexico', region: '', tz: 'America/Mexico_City', aliases: 'pbc' },
  { id: 'qro', name: 'Querétaro', country: 'Mexico', region: '', tz: 'America/Mexico_City', aliases: 'qro,queretaro' },
  { id: 'gua', name: 'Guatemala City', country: 'Guatemala', region: '', tz: 'America/Guatemala', aliases: 'gua' },
  { id: 'sap2', name: 'San Pedro Sula', country: 'Honduras', region: '', tz: 'America/Tegucigalpa', aliases: 'sap,san pedro sula' },
  { id: 'tgu', name: 'Tegucigalpa', country: 'Honduras', region: '', tz: 'America/Tegucigalpa', aliases: 'tgu' },
  { id: 'sal', name: 'San Salvador', country: 'El Salvador', region: '', tz: 'America/El_Salvador', aliases: 'sal' },
  { id: 'mga', name: 'Managua', country: 'Nicaragua', region: '', tz: 'America/Managua', aliases: 'mga' },
  { id: 'bze', name: 'Belize City', country: 'Belize', region: '', tz: 'America/Belize', aliases: 'bze' },
  { id: 'nas', name: 'Nassau', country: 'Bahamas', region: '', tz: 'America/Nassau', aliases: 'nas' },
  { id: 'bda', name: 'Hamilton', country: 'Bermuda', region: '', tz: 'Atlantic/Bermuda', aliases: 'bda' },
  { id: 'bgw', name: 'Bridgetown', country: 'Barbados', region: '', tz: 'America/Barbados', aliases: 'bgi,bridgetown' },
  { id: 'gnd', name: 'St. George\'s', country: 'Grenada', region: '', tz: 'America/Grenada', aliases: 'gnd' },
  { id: 'anu', name: 'St. John\'s', country: 'Antigua and Barbuda', region: '', tz: 'America/Antigua', aliases: 'anu' },
  { id: 'sxm', name: 'Philipsburg', country: 'Sint Maarten', region: '', tz: 'America/Lower_Princes', aliases: 'sxm' },
  { id: 'willem', name: 'Willemstad', country: 'Curaçao', region: '', tz: 'America/Curacao', aliases: 'cur,curacao' },
  { id: 'aua', name: 'Oranjestad', country: 'Aruba', region: '', tz: 'America/Aruba', aliases: 'aua' },
  { id: 'pap', name: 'Port-au-Prince', country: 'Haiti', region: '', tz: 'America/Port-au-Prince', aliases: 'pap' },
  { id: 'ggt', name: 'George Town', country: 'Cayman Islands', region: '', tz: 'America/Cayman', aliases: 'gcm,cayman' },
  { id: 'ros', name: 'Rosario', country: 'Argentina', region: '', tz: 'America/Argentina/Buenos_Aires', aliases: 'ros' },
  { id: 'ush', name: 'Ushuaia', country: 'Argentina', region: 'Tierra del Fuego', tz: 'America/Argentina/Ushuaia', aliases: 'ush' },
  { id: 'brc', name: 'San Carlos de Bariloche', country: 'Argentina', region: '', tz: 'America/Argentina/Buenos_Aires', aliases: 'brc,bariloche' },
  { id: 'res', name: 'Resistencia', country: 'Argentina', region: '', tz: 'America/Argentina/Cordoba', aliases: 'res' },
  { id: 'vvi', name: 'Santa Cruz de la Sierra', country: 'Bolivia', region: '', tz: 'America/La_Paz', aliases: 'vvi' },
  { id: 'ari', name: 'Arica', country: 'Chile', region: '', tz: 'America/Santiago', aliases: 'ari' },
  { id: 'pmc', name: 'Puerto Montt', country: 'Chile', region: '', tz: 'America/Santiago', aliases: 'pmc' },
  { id: 'eas', name: 'Easter Island', country: 'Chile', region: '', tz: 'Pacific/Easter', aliases: 'ipc,rapa nui' },
  { id: 'aqp', name: 'Arequipa', country: 'Peru', region: '', tz: 'America/Lima', aliases: 'aqp' },
  { id: 'cuz', name: 'Cusco', country: 'Peru', region: '', tz: 'America/Lima', aliases: 'cuz,cusco,cuzco' },
  { id: 'baq', name: 'Barranquilla', country: 'Colombia', region: '', tz: 'America/Bogota', aliases: 'baq' },
  { id: 'ctg', name: 'Cartagena', country: 'Colombia', region: '', tz: 'America/Bogota', aliases: 'ctg' },
  { id: 'uio2', name: 'Cuenca', country: 'Ecuador', region: '', tz: 'America/Guayaquil', aliases: 'cue,cuenca' },
  { id: 'gps', name: 'Puerto Ayora', country: 'Ecuador', region: 'Galápagos', tz: 'Pacific/Galapagos', aliases: 'gps,galapagos' },
  { id: 'mar', name: 'Maracaibo', country: 'Venezuela', region: '', tz: 'America/Caracas', aliases: 'mar' },
  { id: 'pmv', name: 'Porlamar', country: 'Venezuela', region: '', tz: 'America/Caracas', aliases: 'pmv' },
  { id: 'cay', name: 'Cayenne', country: 'French Guiana', region: '', tz: 'America/Cayenne', aliases: 'cay' },
  { id: 'fcz', name: 'Stanley', country: 'Falkland Islands', region: '', tz: 'Atlantic/Stanley', aliases: 'psy,falklands' },
  { id: 'gru2', name: 'Campinas', country: 'Brazil', region: 'São Paulo', tz: 'America/Sao_Paulo', aliases: 'vcp,campinas' },
  { id: 'rao', name: 'Ribeirão Preto', country: 'Brazil', region: 'São Paulo', tz: 'America/Sao_Paulo', aliases: 'rao,ribeirao' },
  { id: 'sjp', name: 'São José do Rio Preto', country: 'Brazil', region: 'São Paulo', tz: 'America/Sao_Paulo', aliases: 'sjp' },
  { id: 'jdi', name: 'Juiz de Fora', country: 'Brazil', region: 'Minas Gerais', tz: 'America/Sao_Paulo', aliases: 'jdf' },
  { id: 'udi', name: 'Uberlândia', country: 'Brazil', region: 'Minas Gerais', tz: 'America/Sao_Paulo', aliases: 'udi,uberlandia' },
  { id: 'cwb2', name: 'Londrina', country: 'Brazil', region: 'Paraná', tz: 'America/Sao_Paulo', aliases: 'ldn,londrina' },
  { id: 'mcz', name: 'Maceió', country: 'Brazil', region: 'Alagoas', tz: 'America/Maceio', aliases: 'mcz,maceio' },
  { id: 'aju', name: 'Aracaju', country: 'Brazil', region: 'Sergipe', tz: 'America/Maceio', aliases: 'aju' },
  { id: 'bvz', name: 'Boa Vista', country: 'Brazil', region: 'Roraima', tz: 'America/Boa_Vista', aliases: 'bvb,boa vista' },
  { id: 'stm', name: 'Santarém', country: 'Brazil', region: 'Pará', tz: 'America/Santarem', aliases: 'stm,santarem' },
  { id: 'fnn', name: 'Fernando de Noronha', country: 'Brazil', region: 'Pernambuco', tz: 'America/Noronha', aliases: 'fns,noronha' },
  { id: 'and', name: 'Andorra la Vella', country: 'Andorra', region: '', tz: 'Europe/Andorra', aliases: 'aldy,andorra' },
  { id: 'mona', name: 'Monaco', country: 'Monaco', region: '', tz: 'Europe/Monaco', aliases: 'mcm' },
  { id: 'smi', name: 'San Marino', country: 'San Marino', region: '', tz: 'Europe/San_Marino', aliases: 'smi' },
  { id: 'vat', name: 'Vatican City', country: 'Vatican City', region: '', tz: 'Europe/Vatican', aliases: 'vat' },
  { id: 'lie', name: 'Vaduz', country: 'Liechtenstein', region: '', tz: 'Europe/Vaduz', aliases: 'lie,vaduz' },
  { id: 'pod', name: 'Podgorica', country: 'Montenegro', region: '', tz: 'Europe/Podgorica', aliases: 'tgv,podgorica' },
  { id: 'pristina', name: 'Pristina', country: 'Kosovo', region: '', tz: 'Europe/Belgrade', aliases: 'prn,pristina' },
  { id: 'sar', name: 'Sarajevo', country: 'Bosnia and Herzegovina', region: '', tz: 'Europe/Sarajevo', aliases: 'sjj,sarajevo' },
  { id: 'chi2', name: 'Chișinău', country: 'Moldova', region: '', tz: 'Europe/Chisinau', aliases: 'kiv,chisinau' },
  { id: 'msq', name: 'Minsk', country: 'Belarus', region: '', tz: 'Europe/Minsk', aliases: 'msq' },
  { id: 'tll2', name: 'Kaliningrad', country: 'Russia', region: '', tz: 'Europe/Kaliningrad', aliases: 'kgd,kaliningrad' },
  { id: 'led', name: 'Saint Petersburg', country: 'Russia', region: '', tz: 'Europe/Moscow', aliases: 'led,petersburg,spb' },
  { id: 'ovb', name: 'Novosibirsk', country: 'Russia', region: '', tz: 'Asia/Novosibirsk', aliases: 'ovb,novosibirsk' },
  { id: 'svx', name: 'Yekaterinburg', country: 'Russia', region: '', tz: 'Asia/Yekaterinburg', aliases: 'svx,ekaterinburg' },
  { id: 'ovb2', name: 'Omsk', country: 'Russia', region: '', tz: 'Asia/Omsk', aliases: 'oms,omsk' },
  { id: 'ikt', name: 'Irkutsk', country: 'Russia', region: '', tz: 'Asia/Irkutsk', aliases: 'ikt' },
  { id: 'yak', name: 'Yakutsk', country: 'Russia', region: '', tz: 'Asia/Yakutsk', aliases: 'yak' },
  { id: 'vvo', name: 'Vladivostok', country: 'Russia', region: '', tz: 'Asia/Vladivostok', aliases: 'vvo' },
  { id: 'pkc', name: 'Petropavlovsk-Kamchatsky', country: 'Russia', region: '', tz: 'Asia/Kamchatka', aliases: 'pkc,kamchatka' },
  { id: 'mag', name: 'Magadan', country: 'Russia', region: '', tz: 'Asia/Magadan', aliases: 'gdx,magadan' },
  { id: 'kja', name: 'Krasnoyarsk', country: 'Russia', region: '', tz: 'Asia/Krasnoyarsk', aliases: 'kja' },
  { id: 'gyd', name: 'Samara', country: 'Russia', region: '', tz: 'Europe/Samara', aliases: 'kuf,samara' },
  { id: 'voz', name: 'Voronezh', country: 'Russia', region: '', tz: 'Europe/Moscow', aliases: 'voz' },
  { id: 'kzn', name: 'Kazan', country: 'Russia', region: '', tz: 'Europe/Moscow', aliases: 'kzn' },
  { id: 'rov', name: 'Rostov-on-Don', country: 'Russia', region: '', tz: 'Europe/Moscow', aliases: 'rov' },
  { id: 'aer', name: 'Sochi', country: 'Russia', region: '', tz: 'Europe/Moscow', aliases: 'aer,sochi' },
  { id: 'ods', name: 'Odesa', country: 'Ukraine', region: '', tz: 'Europe/Kyiv', aliases: 'ods,odessa' },
  { id: 'hrk', name: 'Kharkiv', country: 'Ukraine', region: '', tz: 'Europe/Kyiv', aliases: 'hrk' },
  { id: 'lwo', name: 'Lviv', country: 'Ukraine', region: '', tz: 'Europe/Kyiv', aliases: 'lwo,lwow' },
  { id: 'gva2', name: 'Lausanne', country: 'Switzerland', region: '', tz: 'Europe/Zurich', aliases: 'qls,lausanne' },
  { id: 'inn', name: 'Innsbruck', country: 'Austria', region: '', tz: 'Europe/Vienna', aliases: 'inn' },
  { id: 'szg', name: 'Salzburg', country: 'Austria', region: '', tz: 'Europe/Vienna', aliases: 'szg' },
  { id: 'bio', name: 'Bilbao', country: 'Spain', region: '', tz: 'Europe/Madrid', aliases: 'bio' },
  { id: 'agp', name: 'Málaga', country: 'Spain', region: '', tz: 'Europe/Madrid', aliases: 'agp,malaga' },
  { id: 'pmi', name: 'Palma', country: 'Spain', region: 'Balearic Islands', tz: 'Europe/Madrid', aliases: 'pmi,mallorca' },
  { id: 'lpa', name: 'Las Palmas', country: 'Spain', region: 'Canary Islands', tz: 'Atlantic/Canary', aliases: 'lpa,gran canaria' },
  { id: 'tci', name: 'Santa Cruz de Tenerife', country: 'Spain', region: 'Canary Islands', tz: 'Atlantic/Canary', aliases: 'tci,tenerife' },
  { id: 'fnc', name: 'Funchal', country: 'Portugal', region: 'Madeira', tz: 'Atlantic/Madeira', aliases: 'fnc,madeira' },
  { id: 'pdl', name: 'Ponta Delgada', country: 'Portugal', region: 'Azores', tz: 'Atlantic/Azores', aliases: 'pdl,azores' },
  { id: 'ace', name: 'Lajes', country: 'Portugal', region: 'Azores', tz: 'Atlantic/Azores', aliases: 'ter,terceira' },
  { id: 'bod', name: 'Bordeaux', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'bod' },
  { id: 'nce', name: 'Nice', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'nce' },
  { id: 'tls', name: 'Toulouse', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'tls' },
  { id: 'sxb', name: 'Strasbourg', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'sxb' },
  { id: 'nte', name: 'Nantes', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'nte' },
  { id: 'lil', name: 'Lille', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'lil' },
  { id: 'rns', name: 'Rennes', country: 'France', region: '', tz: 'Europe/Paris', aliases: 'rns' },
  { id: 'rtm', name: 'Rotterdam', country: 'Netherlands', region: '', tz: 'Europe/Amsterdam', aliases: 'rtm' },
  { id: 'ein', name: 'Eindhoven', country: 'Netherlands', region: '', tz: 'Europe/Amsterdam', aliases: 'ein' },
  { id: 'anr', name: 'Antwerp', country: 'Belgium', region: '', tz: 'Europe/Brussels', aliases: 'anr' },
  { id: 'ghn', name: 'Ghent', country: 'Belgium', region: '', tz: 'Europe/Brussels', aliases: 'ghn,gent' },
  { id: 'cph2', name: 'Aarhus', country: 'Denmark', region: '', tz: 'Europe/Copenhagen', aliases: 'aar,aarhus' },
  { id: 'bgo', name: 'Bergen', country: 'Norway', region: '', tz: 'Europe/Oslo', aliases: 'bgo' },
  { id: 'trd', name: 'Trondheim', country: 'Norway', region: '', tz: 'Europe/Oslo', aliases: 'trd' },
  { id: 'tmp', name: 'Tampere', country: 'Finland', region: '', tz: 'Europe/Helsinki', aliases: 'tmp' },
  { id: 'tku', name: 'Turku', country: 'Finland', region: '', tz: 'Europe/Helsinki', aliases: 'tku' },
  { id: 'wro', name: 'Wrocław', country: 'Poland', region: '', tz: 'Europe/Warsaw', aliases: 'wro,wroclaw' },
  { id: 'poz', name: 'Poznań', country: 'Poland', region: '', tz: 'Europe/Warsaw', aliases: 'poz,poznan' },
  { id: 'ktw', name: 'Katowice', country: 'Poland', region: '', tz: 'Europe/Warsaw', aliases: 'ktw' },
  { id: 'brq', name: 'Brno', country: 'Czechia', region: '', tz: 'Europe/Prague', aliases: 'brq' },
  { id: 'deb', name: 'Debrecen', country: 'Hungary', region: '', tz: 'Europe/Budapest', aliases: 'deb' },
  { id: 'skg', name: 'Thessaloniki', country: 'Greece', region: '', tz: 'Europe/Athens', aliases: 'skg' },
  { id: 'her', name: 'Heraklion', country: 'Greece', region: 'Crete', tz: 'Europe/Athens', aliases: 'her,crete' },
  { id: 'ayt', name: 'Antalya', country: 'Türkiye', region: '', tz: 'Europe/Istanbul', aliases: 'ayt' },
  { id: 'adb', name: 'İzmir', country: 'Türkiye', region: '', tz: 'Europe/Istanbul', aliases: 'adb,izmir' },
  { id: 'esb', name: 'Ankara', country: 'Türkiye', region: '', tz: 'Europe/Istanbul', aliases: 'esb,ankara' },
  { id: 'cob', name: 'Cluj-Napoca', country: 'Romania', region: '', tz: 'Europe/Bucharest', aliases: 'clj,cluj' },
  { id: 'tsr', name: 'Timișoara', country: 'Romania', region: '', tz: 'Europe/Bucharest', aliases: 'tsr,timisoara' },
  { id: 'var', name: 'Varna', country: 'Bulgaria', region: '', tz: 'Europe/Sofia', aliases: 'var' },
  { id: 'plov', name: 'Plovdiv', country: 'Bulgaria', region: '', tz: 'Europe/Sofia', aliases: 'pdv,plovdiv' },
  { id: 'spl', name: 'Split', country: 'Croatia', region: '', tz: 'Europe/Zagreb', aliases: 'spu,split' },
  { id: 'dbv', name: 'Dubrovnik', country: 'Croatia', region: '', tz: 'Europe/Zagreb', aliases: 'dbv' },
  { id: 'beg2', name: 'Novi Sad', country: 'Serbia', region: '', tz: 'Europe/Belgrade', aliases: 'qnd,novi sad' },
  { id: 'gci', name: 'St. Peter Port', country: 'Guernsey', region: '', tz: 'Europe/Guernsey', aliases: 'gci' },
  { id: 'jey', name: 'Saint Helier', country: 'Jersey', region: '', tz: 'Europe/Jersey', aliases: 'jey' },
  { id: 'iom', name: 'Douglas', country: 'Isle of Man', region: '', tz: 'Europe/Isle_of_Man', aliases: 'iom' },
  { id: 'gibr', name: 'Gibraltar', country: 'Gibraltar', region: '', tz: 'Europe/Gibraltar', aliases: 'gib' },
  { id: 'fao', name: 'Faroe Islands', country: 'Faroe Islands', region: 'Tórshavn', tz: 'Atlantic/Faroe', aliases: 'fae,torshavn' },
  { id: 'goh', name: 'Nuuk', country: 'Greenland', region: '', tz: 'America/Nuuk', aliases: 'goh,godthab' },
  { id: 'jck', name: 'Ittoqqortoormiit', country: 'Greenland', region: '', tz: 'America/Scoresbysund', aliases: 'scoresbysund' },
  { id: 'thu', name: 'Qaanaaq', country: 'Greenland', region: '', tz: 'America/Thule', aliases: 'thu,thule' },
  { id: 'lba', name: 'Leeds', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'lba' },
  { id: 'lpl', name: 'Liverpool', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'lpl' },
  { id: 'ncl', name: 'Newcastle', country: 'United Kingdom', region: 'England', tz: 'Europe/London', aliases: 'ncl' },
  { id: 'cwl', name: 'Cardiff', country: 'United Kingdom', region: 'Wales', tz: 'Europe/London', aliases: 'cwl' },
  { id: 'bfs', name: 'Belfast', country: 'United Kingdom', region: 'Northern Ireland', tz: 'Europe/London', aliases: 'bfs' },
  { id: 'inv', name: 'Inverness', country: 'United Kingdom', region: 'Scotland', tz: 'Europe/London', aliases: 'inv' },
  { id: 'ork', name: 'Cork', country: 'Ireland', region: '', tz: 'Europe/Dublin', aliases: 'ork' },
  { id: 'gwyn', name: 'Galway', country: 'Ireland', region: '', tz: 'Europe/Dublin', aliases: 'gwyn,galway' },
  { id: 'cai2', name: 'Alexandria', country: 'Egypt', region: '', tz: 'Africa/Cairo', aliases: 'aly,alexandria' },
  { id: 'ssh', name: 'Sharm El Sheikh', country: 'Egypt', region: '', tz: 'Africa/Cairo', aliases: 'ssh' },
  { id: 'cmn2', name: 'Rabat', country: 'Morocco', region: '', tz: 'Africa/Casablanca', aliases: 'rba,rabat' },
  { id: 'tng', name: 'Tangier', country: 'Morocco', region: '', tz: 'Africa/Casablanca', aliases: 'tng' },
  { id: 'orn', name: 'Oran', country: 'Algeria', region: '', tz: 'Africa/Algiers', aliases: 'orn' },
  { id: 'tip', name: 'Tripoli', country: 'Libya', region: '', tz: 'Africa/Tripoli', aliases: 'tip' },
  { id: 'ben', name: 'Benghazi', country: 'Libya', region: '', tz: 'Africa/Tripoli', aliases: 'ben' },
  { id: 'krt', name: 'Khartoum', country: 'Sudan', region: '', tz: 'Africa/Khartoum', aliases: 'krt' },
  { id: 'juba', name: 'Juba', country: 'South Sudan', region: '', tz: 'Africa/Juba', aliases: 'juba' },
  { id: 'asm', name: 'Asmara', country: 'Eritrea', region: '', tz: 'Africa/Asmara', aliases: 'asm' },
  { id: 'djb', name: 'Djibouti', country: 'Djibouti', region: '', tz: 'Africa/Djibouti', aliases: 'jib,djibouti' },
  { id: 'mgq', name: 'Mogadishu', country: 'Somalia', region: '', tz: 'Africa/Mogadishu', aliases: 'mgq' },
  { id: 'sezl', name: 'Victoria', country: 'Seychelles', region: '', tz: 'Indian/Mahe', aliases: 'sez,seychelles' },
  { id: 'mru', name: 'Port Louis', country: 'Mauritius', region: '', tz: 'Indian/Mauritius', aliases: 'mru' },
  { id: 'run', name: 'Saint-Denis', country: 'Réunion', region: '', tz: 'Indian/Reunion', aliases: 'run,reunion' },
  { id: 'tmm', name: 'Antananarivo', country: 'Madagascar', region: '', tz: 'Indian/Antananarivo', aliases: 'tnr,antananarivo' },
  { id: 'mjm', name: 'Moroni', country: 'Comoros', region: '', tz: 'Indian/Comoro', aliases: 'haj,moroni' },
  { id: 'ssg', name: 'Malabo', country: 'Equatorial Guinea', region: '', tz: 'Africa/Malabo', aliases: 'ssg' },
  { id: 'ssg2', name: 'São Tomé', country: 'São Tomé and Príncipe', region: '', tz: 'Africa/Sao_Tome', aliases: 'tms,sao tome' },
  { id: 'lxb', name: 'Libreville', country: 'Gabon', region: '', tz: 'Africa/Libreville', aliases: 'lbv' },
  { id: 'brazz', name: 'Brazzaville', country: 'Republic of the Congo', region: '', tz: 'Africa/Brazzaville', aliases: 'bzv' },
  { id: 'fiha', name: 'Kinshasa', country: 'DR Congo', region: '', tz: 'Africa/Kinshasa', aliases: 'fih,kinshasa' },
  { id: 'fbm', name: 'Lubumbashi', country: 'DR Congo', region: '', tz: 'Africa/Lubumbashi', aliases: 'fbm' },
  { id: 'buj', name: 'Bujumbura', country: 'Burundi', region: '', tz: 'Africa/Bujumbura', aliases: 'bjm,bujumbura' },
  { id: 'kgl', name: 'Kigali', country: 'Rwanda', region: '', tz: 'Africa/Kigali', aliases: 'kgl' },
  { id: 'lil2', name: 'Lilongwe', country: 'Malawi', region: '', tz: 'Africa/Blantyre', aliases: 'llw,lilongwe' },
  { id: 'blz', name: 'Blantyre', country: 'Malawi', region: '', tz: 'Africa/Blantyre', aliases: 'blz' },
  { id: 'gbe', name: 'Gaborone', country: 'Botswana', region: '', tz: 'Africa/Gaborone', aliases: 'gbe' },
  { id: 'mts', name: 'Mbabane', country: 'Eswatini', region: '', tz: 'Africa/Mbabane', aliases: 'mts,eswatini' },
  { id: 'msu', name: 'Maseru', country: 'Lesotho', region: '', tz: 'Africa/Maseru', aliases: 'msu' },
  { id: 'dur', name: 'Durban', country: 'South Africa', region: '', tz: 'Africa/Johannesburg', aliases: 'dur' },
  { id: 'plz', name: 'Gqeberha', country: 'South Africa', region: '', tz: 'Africa/Johannesburg', aliases: 'plz,port elizabeth' },
  { id: 'bfv', name: 'Bloemfontein', country: 'South Africa', region: '', tz: 'Africa/Johannesburg', aliases: 'bfn,bloemfontein' },
  { id: 'ptu', name: 'Pretoria', country: 'South Africa', region: '', tz: 'Africa/Johannesburg', aliases: 'pry,pretoria,tshwane' },
  { id: 'wdh2', name: 'Walvis Bay', country: 'Namibia', region: '', tz: 'Africa/Windhoek', aliases: 'wvb' },
  { id: 'lad2', name: 'Benguela', country: 'Angola', region: '', tz: 'Africa/Luanda', aliases: 'bug,benguela' },
  { id: 'coo', name: 'Cotonou', country: 'Benin', region: '', tz: 'Africa/Porto-Novo', aliases: 'coo' },
  { id: 'lfw', name: 'Lomé', country: 'Togo', region: '', tz: 'Africa/Lome', aliases: 'lfw,lome' },
  { id: 'oua', name: 'Ouagadougou', country: 'Burkina Faso', region: '', tz: 'Africa/Ouagadougou', aliases: 'oua' },
  { id: 'bko', name: 'Bamako', country: 'Mali', region: '', tz: 'Africa/Bamako', aliases: 'bko' },
  { id: 'nim', name: 'Niamey', country: 'Niger', region: '', tz: 'Africa/Niamey', aliases: 'nim' },
  { id: 'ndj', name: 'N\'Djamena', country: 'Chad', region: '', tz: 'Africa/Ndjamena', aliases: 'ndj' },
  { id: 'bgi2', name: 'Bangui', country: 'Central African Republic', region: '', tz: 'Africa/Bangui', aliases: 'baf,bangui' },
  { id: 'yde', name: 'Yaoundé', country: 'Cameroon', region: '', tz: 'Africa/Douala', aliases: 'nsi,yaounde' },
  { id: 'dla', name: 'Douala', country: 'Cameroon', region: '', tz: 'Africa/Douala', aliases: 'dla' },
  { id: 'abu', name: 'Abuja', country: 'Nigeria', region: '', tz: 'Africa/Lagos', aliases: 'abu,abuja' },
  { id: 'kan', name: 'Kano', country: 'Nigeria', region: '', tz: 'Africa/Lagos', aliases: 'kan' },
  { id: 'phc', name: 'Port Harcourt', country: 'Nigeria', region: '', tz: 'Africa/Lagos', aliases: 'phc' },
  { id: 'acc2', name: 'Kumasi', country: 'Ghana', region: '', tz: 'Africa/Accra', aliases: 'kusi,kumasi' },
  { id: 'fna', name: 'Freetown', country: 'Sierra Leone', region: '', tz: 'Africa/Freetown', aliases: 'fna' },
  { id: 'rob', name: 'Monrovia', country: 'Liberia', region: '', tz: 'Africa/Monrovia', aliases: 'rob' },
  { id: 'cky', name: 'Conakry', country: 'Guinea', region: '', tz: 'Africa/Conakry', aliases: 'cky' },
  { id: 'oxb', name: 'Bissau', country: 'Guinea-Bissau', region: '', tz: 'Africa/Bissau', aliases: 'oxb' },
  { id: 'bjl', name: 'Banjul', country: 'Gambia', region: '', tz: 'Africa/Banjul', aliases: 'bjl' },
  { id: 'nkc', name: 'Nouakchott', country: 'Mauritania', region: '', tz: 'Africa/Nouakchott', aliases: 'nkc' },
  { id: 'rai', name: 'Praia', country: 'Cabo Verde', region: '', tz: 'Atlantic/Cape_Verde', aliases: 'rai,cape verde' },
  { id: 'sid', name: 'Mindelo', country: 'Cabo Verde', region: '', tz: 'Atlantic/Cape_Verde', aliases: 'vxeh,mindelo' },
  { id: 'dam', name: 'Damascus', country: 'Syria', region: '', tz: 'Asia/Damascus', aliases: 'dam' },
  { id: 'bgw2', name: 'Baghdad', country: 'Iraq', region: '', tz: 'Asia/Baghdad', aliases: 'bgw,baghdad' },
  { id: 'ebz', name: 'Erbil', country: 'Iraq', region: '', tz: 'Asia/Baghdad', aliases: 'ebz,erbil' },
  { id: 'sah', name: 'Sana\'a', country: 'Yemen', region: '', tz: 'Asia/Aden', aliases: 'sah,sanaa' },
  { id: 'ade', name: 'Aden', country: 'Yemen', region: '', tz: 'Asia/Aden', aliases: 'ade' },
  { id: 'mct2', name: 'Salalah', country: 'Oman', region: '', tz: 'Asia/Muscat', aliases: 'sll,salalah' },
  { id: 'elq', name: 'Dammam', country: 'Saudi Arabia', region: '', tz: 'Asia/Riyadh', aliases: 'dmm,dammam' },
  { id: 'med', name: 'Medina', country: 'Saudi Arabia', region: '', tz: 'Asia/Riyadh', aliases: 'med,madinah' },
  { id: 'mak', name: 'Mecca', country: 'Saudi Arabia', region: '', tz: 'Asia/Riyadh', aliases: 'mak,makkah' },
  { id: 'shj', name: 'Sharjah', country: 'United Arab Emirates', region: '', tz: 'Asia/Dubai', aliases: 'shj' },
  { id: 'ajt', name: 'Ajman', country: 'United Arab Emirates', region: '', tz: 'Asia/Dubai', aliases: 'ajt' },
  { id: 'fjr', name: 'Fujairah', country: 'United Arab Emirates', region: '', tz: 'Asia/Dubai', aliases: 'fjr' },
  { id: 'kbl', name: 'Kabul', country: 'Afghanistan', region: '', tz: 'Asia/Kabul', aliases: 'kbl' },
  { id: 'asb', name: 'Ashgabat', country: 'Turkmenistan', region: '', tz: 'Asia/Ashgabat', aliases: 'asb' },
  { id: 'fru', name: 'Bishkek', country: 'Kyrgyzstan', region: '', tz: 'Asia/Bishkek', aliases: 'fru,bishkek' },
  { id: 'dyu', name: 'Dushanbe', country: 'Tajikistan', region: '', tz: 'Asia/Dushanbe', aliases: 'dyu' },
  { id: 'ura', name: 'Oral', country: 'Kazakhstan', region: '', tz: 'Asia/Oral', aliases: 'ura' },
  { id: 'cit', name: 'Aqtobe', country: 'Kazakhstan', region: '', tz: 'Asia/Aqtobe', aliases: 'akx,aqtobe' },
  { id: 'cit2', name: 'Qyzylorda', country: 'Kazakhstan', region: '', tz: 'Asia/Qyzylorda', aliases: 'kzo,qyzylorda' },
  { id: 'sel2', name: 'Pyongyang', country: 'North Korea', region: '', tz: 'Asia/Pyongyang', aliases: 'fnj,pyongyang' },
  { id: 'uln2', name: 'Erdenet', country: 'Mongolia', region: '', tz: 'Asia/Ulaanbaatar', aliases: 'erdenet' },
  { id: 'hov', name: 'Hovd', country: 'Mongolia', region: '', tz: 'Asia/Hovd', aliases: 'hovd' },
  { id: 'cgo', name: 'Zhengzhou', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'cgo' },
  { id: 'xiy', name: 'Xi\'an', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'xiy,xian' },
  { id: 'nkg', name: 'Nanjing', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'nkg' },
  { id: 'tna', name: 'Jinan', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'tna' },
  { id: 'tsn', name: 'Tianjin', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'tsn' },
  { id: 'she', name: 'Shenyang', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'she' },
  { id: 'dlc', name: 'Dalian', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'dlc' },
  { id: 'hrb', name: 'Harbin', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'hrb' },
  { id: 'kmg', name: 'Kunming', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'kmg' },
  { id: 'xmn', name: 'Xiamen', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'xmn' },
  { id: 'foc', name: 'Fuzhou', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'foc' },
  { id: 'hgh', name: 'Hangzhou', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'hgh' },
  { id: 'szv', name: 'Suzhou', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'szv' },
  { id: 'urc', name: 'Ürümqi', country: 'China', region: '', tz: 'Asia/Urumqi', aliases: 'urc,urumqi' },
  { id: 'lhw', name: 'Lanzhou', country: 'China', region: '', tz: 'Asia/Shanghai', aliases: 'lhw' },
  { id: 'lxa', name: 'Lhasa', country: 'China', region: 'Tibet', tz: 'Asia/Shanghai', aliases: 'lxa,lhasa' },
  { id: 'hkt', name: 'Phuket', country: 'Thailand', region: '', tz: 'Asia/Bangkok', aliases: 'hkt' },
  { id: 'cnx', name: 'Chiang Mai', country: 'Thailand', region: '', tz: 'Asia/Bangkok', aliases: 'cnx' },
  { id: 'vte', name: 'Vientiane', country: 'Laos', region: '', tz: 'Asia/Vientiane', aliases: 'vte' },
  { id: 'bwn', name: 'Bandar Seri Begawan', country: 'Brunei', region: '', tz: 'Asia/Brunei', aliases: 'bwn,brunei' },
  { id: 'dili', name: 'Dili', country: 'Timor-Leste', region: '', tz: 'Asia/Dili', aliases: 'dil,dili' },
  { id: 'sub', name: 'Surabaya', country: 'Indonesia', region: '', tz: 'Asia/Jakarta', aliases: 'sub' },
  { id: 'mes', name: 'Medan', country: 'Indonesia', region: '', tz: 'Asia/Jakarta', aliases: 'mes,kno' },
  { id: 'upg', name: 'Makassar', country: 'Indonesia', region: '', tz: 'Asia/Makassar', aliases: 'upg' },
  { id: 'jog', name: 'Yogyakarta', country: 'Indonesia', region: '', tz: 'Asia/Jakarta', aliases: 'jog' },
  { id: 'bpn', name: 'Balikpapan', country: 'Indonesia', region: '', tz: 'Asia/Makassar', aliases: 'bpn' },
  { id: 'djj', name: 'Jayapura', country: 'Indonesia', region: 'Papua', tz: 'Asia/Jayapura', aliases: 'djj' },
  { id: 'ceb', name: 'Cebu', country: 'Philippines', region: '', tz: 'Asia/Manila', aliases: 'ceb' },
  { id: 'dvo', name: 'Davao', country: 'Philippines', region: '', tz: 'Asia/Manila', aliases: 'dvo' },
  { id: 'mnl2', name: 'Quezon City', country: 'Philippines', region: '', tz: 'Asia/Manila', aliases: 'quezon' },
  { id: 'pen', name: 'George Town', country: 'Malaysia', region: 'Penang', tz: 'Asia/Kuala_Lumpur', aliases: 'pen,penang' },
  { id: 'jhb', name: 'Johor Bahru', country: 'Malaysia', region: '', tz: 'Asia/Kuala_Lumpur', aliases: 'jhb' },
  { id: 'bki', name: 'Kota Kinabalu', country: 'Malaysia', region: 'Sabah', tz: 'Asia/Kuching', aliases: 'bki' },
  { id: 'kch', name: 'Kuching', country: 'Malaysia', region: 'Sarawak', tz: 'Asia/Kuching', aliases: 'kch' },
  { id: 'mle', name: 'Malé', country: 'Maldives', region: '', tz: 'Indian/Maldives', aliases: 'mle,maldives' },
  { id: 'thim', name: 'Thimphu', country: 'Bhutan', region: '', tz: 'Asia/Thimphu', aliases: 'pbh,thimphu' },
  { id: 'ccu2', name: 'Guwahati', country: 'India', region: 'Assam', tz: 'Asia/Kolkata', aliases: 'gau,guwahati' },
  { id: 'cok', name: 'Kochi', country: 'India', region: 'Kerala', tz: 'Asia/Kolkata', aliases: 'cok,cochin' },
  { id: 'trv', name: 'Thiruvananthapuram', country: 'India', region: 'Kerala', tz: 'Asia/Kolkata', aliases: 'trv' },
  { id: 'goi', name: 'Panaji', country: 'India', region: 'Goa', tz: 'Asia/Kolkata', aliases: 'goi,goa' },
  { id: 'ixc', name: 'Chandigarh', country: 'India', region: '', tz: 'Asia/Kolkata', aliases: 'ixc' },
  { id: 'lko', name: 'Lucknow', country: 'India', region: 'Uttar Pradesh', tz: 'Asia/Kolkata', aliases: 'lko' },
  { id: 'pat', name: 'Patna', country: 'India', region: 'Bihar', tz: 'Asia/Kolkata', aliases: 'pat' },
  { id: 'bbi', name: 'Bhubaneswar', country: 'India', region: 'Odisha', tz: 'Asia/Kolkata', aliases: 'bbi' },
  { id: 'ixb', name: 'Bagdogra', country: 'India', region: 'West Bengal', tz: 'Asia/Kolkata', aliases: 'ixb,siliguri' },
  { id: 'ixz', name: 'Port Blair', country: 'India', region: 'Andaman and Nicobar', tz: 'Asia/Kolkata', aliases: 'ixz' },
  { id: 'ixm', name: 'Madurai', country: 'India', region: 'Tamil Nadu', tz: 'Asia/Kolkata', aliases: 'ixm' },
  { id: 'vtz', name: 'Visakhapatnam', country: 'India', region: 'Andhra Pradesh', tz: 'Asia/Kolkata', aliases: 'vtz' },
  { id: 'nag', name: 'Nagpur', country: 'India', region: 'Maharashtra', tz: 'Asia/Kolkata', aliases: 'nag' },
  { id: 'idr', name: 'Indore', country: 'India', region: 'Madhya Pradesh', tz: 'Asia/Kolkata', aliases: 'idr' },
  { id: 'bho', name: 'Bhopal', country: 'India', region: 'Madhya Pradesh', tz: 'Asia/Kolkata', aliases: 'bho' },
  { id: 'jdh', name: 'Jodhpur', country: 'India', region: 'Rajasthan', tz: 'Asia/Kolkata', aliases: 'jdh' },
  { id: 'udi2', name: 'Surat', country: 'India', region: 'Gujarat', tz: 'Asia/Kolkata', aliases: 'stv,surat' },
  { id: 'amd2', name: 'Vadodara', country: 'India', region: 'Gujarat', tz: 'Asia/Kolkata', aliases: 'bdq,vadodara' },
  { id: 'fuk', name: 'Fukuoka', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'fuk' },
  { id: 'hij', name: 'Hiroshima', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'hij' },
  { id: 'kix2', name: 'Kyoto', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'uky,kyoto' },
  { id: 'oka', name: 'Naha', country: 'Japan', region: 'Okinawa', tz: 'Asia/Tokyo', aliases: 'oka,okinawa' },
  { id: 'sdj', name: 'Sendai', country: 'Japan', region: '', tz: 'Asia/Tokyo', aliases: 'sdj' },
  { id: 'icn2', name: 'Incheon', country: 'South Korea', region: '', tz: 'Asia/Seoul', aliases: 'icn,incheon' },
  { id: 'cju', name: 'Jeju', country: 'South Korea', region: '', tz: 'Asia/Seoul', aliases: 'cju' },
  { id: 'khh', name: 'Kaohsiung', country: 'Taiwan', region: '', tz: 'Asia/Taipei', aliases: 'khh' },
  { id: 'rmq', name: 'Taichung', country: 'Taiwan', region: '', tz: 'Asia/Taipei', aliases: 'rmq' },
  { id: 'mfk', name: 'Macau', country: 'Macau', region: '', tz: 'Asia/Macau', aliases: 'mfm,macau,macao' },
  { id: 'cns', name: 'Cairns', country: 'Australia', region: 'Queensland', tz: 'Australia/Brisbane', aliases: 'cns' },
  { id: 'tso', name: 'Townsville', country: 'Australia', region: 'Queensland', tz: 'Australia/Brisbane', aliases: 'tsv' },
  { id: 'cbr2', name: 'Gold Coast', country: 'Australia', region: 'Queensland', tz: 'Australia/Brisbane', aliases: 'ool,gold coast' },
  { id: 'lst', name: 'Launceston', country: 'Australia', region: 'Tasmania', tz: 'Australia/Hobart', aliases: 'lst' },
  { id: 'asp', name: 'Alice Springs', country: 'Australia', region: 'Northern Territory', tz: 'Australia/Darwin', aliases: 'asp' },
  { id: 'bnk', name: 'Ballina', country: 'Australia', region: 'New South Wales', tz: 'Australia/Sydney', aliases: 'bnk,byron' },
  { id: 'zqn', name: 'Queenstown', country: 'New Zealand', region: '', tz: 'Pacific/Auckland', aliases: 'zqn' },
  { id: 'dud', name: 'Dunedin', country: 'New Zealand', region: '', tz: 'Pacific/Auckland', aliases: 'dud' },
  { id: 'cht', name: 'Waitangi', country: 'New Zealand', region: 'Chatham Islands', tz: 'Pacific/Chatham', aliases: 'cht,chatham' },
  { id: 'pom', name: 'Port Moresby', country: 'Papua New Guinea', region: '', tz: 'Pacific/Port_Moresby', aliases: 'pom' },
  { id: 'hir', name: 'Honiara', country: 'Solomon Islands', region: '', tz: 'Pacific/Guadalcanal', aliases: 'hir' },
  { id: 'vli', name: 'Port Vila', country: 'Vanuatu', region: '', tz: 'Pacific/Efate', aliases: 'vli' },
  { id: 'nan', name: 'Nadi', country: 'Fiji', region: '', tz: 'Pacific/Fiji', aliases: 'nan' },
  { id: 'tbu', name: 'Nuku\'alofa', country: 'Tonga', region: '', tz: 'Pacific/Tongatapu', aliases: 'tbu,tonga' },
  { id: 'fun', name: 'Funafuti', country: 'Tuvalu', region: '', tz: 'Pacific/Funafuti', aliases: 'fun,tuvalu' },
  { id: 'trw', name: 'Tarawa', country: 'Kiribati', region: '', tz: 'Pacific/Tarawa', aliases: 'trw' },
  { id: 'cxi', name: 'Kiritimati', country: 'Kiribati', region: 'Line Islands', tz: 'Pacific/Kiritimati', aliases: 'cxi,christmas island kiribati' },
  { id: 'mdy', name: 'Midway', country: 'United States', region: 'Midway Atoll', tz: 'Pacific/Midway', aliases: 'mdy' },
  { id: 'ppg', name: 'Pago Pago', country: 'American Samoa', region: '', tz: 'Pacific/Pago_Pago', aliases: 'ppg' },
  { id: 'niue', name: 'Alofi', country: 'Niue', region: '', tz: 'Pacific/Niue', aliases: 'iue,alofi,niue' },
  { id: 'wls', name: 'Mata-Utu', country: 'Wallis and Futuna', region: '', tz: 'Pacific/Wallis', aliases: 'wls' },
  { id: 'spn', name: 'Saipan', country: 'Northern Mariana Islands', region: '', tz: 'Pacific/Saipan', aliases: 'spn' },
  { id: 'ror', name: 'Koror', country: 'Palau', region: '', tz: 'Pacific/Palau', aliases: 'ror,palau' },
  { id: 'pni', name: 'Palikir', country: 'Micronesia', region: '', tz: 'Pacific/Pohnpei', aliases: 'pni,pohnpei' },
  { id: 'maj', name: 'Majuro', country: 'Marshall Islands', region: '', tz: 'Pacific/Majuro', aliases: 'maj' },
  { id: 'awk', name: 'Wake Island', country: 'United States', region: '', tz: 'Pacific/Wake', aliases: 'awk,wake' },
  { id: 'nhv', name: 'Nuku Hiva', country: 'French Polynesia', region: 'Marquesas', tz: 'Pacific/Marquesas', aliases: 'nhv,marquesas' },
  { id: 'gmt', name: 'Gambier', country: 'French Polynesia', region: 'Gambier Islands', tz: 'Pacific/Gambier', aliases: 'gmr,gambier' },
  { id: 'avarua', name: 'Avarua', country: 'Cook Islands', region: 'Rarotonga', tz: 'Pacific/Rarotonga', aliases: 'rar,rarotonga,cook islands' },
  { id: 'pitc', name: 'Adamstown', country: 'Pitcairn Islands', region: '', tz: 'Pacific/Pitcairn', aliases: 'pcn,pitcairn' },
  { id: 'cck', name: 'West Island', country: 'Cocos (Keeling) Islands', region: '', tz: 'Indian/Cocos', aliases: 'cck,cocos' },
  { id: 'xch', name: 'Flying Fish Cove', country: 'Christmas Island', region: '', tz: 'Indian/Christmas', aliases: 'xch,christmas island' },
  { id: 'shn', name: 'Jamestown', country: 'Saint Helena', region: '', tz: 'Atlantic/St_Helena', aliases: 'shn,saint helena' },
  { id: 'asi', name: 'Georgetown', country: 'Saint Helena', region: 'Ascension', tz: 'Atlantic/St_Helena', aliases: 'asi,ascension' },
  { id: 'tnn', name: 'Edinburgh of the Seven Seas', country: 'Saint Helena', region: 'Tristan da Cunha', tz: 'Atlantic/St_Helena', aliases: 'tdc,tristan' },
  { id: 'sgs', name: 'King Edward Point', country: 'South Georgia', region: '', tz: 'Atlantic/South_Georgia', aliases: 'sgs' },
  { id: 'mcmurdo', name: 'McMurdo Station', country: 'Antarctica', region: '', tz: 'Antarctica/McMurdo', aliases: 'mcm,mcmurdo' },
  { id: 'casey', name: 'Casey Station', country: 'Antarctica', region: '', tz: 'Antarctica/Casey', aliases: 'casey' },
  { id: 'davis', name: 'Davis Station', country: 'Antarctica', region: '', tz: 'Antarctica/Davis', aliases: 'davis' },
  { id: 'maw', name: 'Mawson Station', country: 'Antarctica', region: '', tz: 'Antarctica/Mawson', aliases: 'mawson' },
  { id: 'pal', name: 'Palmer Station', country: 'Antarctica', region: '', tz: 'Antarctica/Palmer', aliases: 'palmer' },
  { id: 'rol', name: 'Rothera', country: 'Antarctica', region: '', tz: 'Antarctica/Rothera', aliases: 'rothera' },
  { id: 'syowa', name: 'Syowa Station', country: 'Antarctica', region: '', tz: 'Antarctica/Syowa', aliases: 'syowa' },
  { id: 'troll', name: 'Troll Station', country: 'Antarctica', region: '', tz: 'Antarctica/Troll', aliases: 'troll' },
  { id: 'vostok', name: 'Vostok Station', country: 'Antarctica', region: '', tz: 'Antarctica/Vostok', aliases: 'vostok' },
  { id: 'dumont', name: 'Dumont d\'Urville', country: 'Antarctica', region: '', tz: 'Antarctica/DumontDUrville', aliases: 'dumont' },
  { id: 'alg2', name: 'Constantine', country: 'Algeria', region: '', tz: 'Africa/Algiers', aliases: 'czl,constantine' },
  { id: 'cmn3', name: 'Marrakesh', country: 'Morocco', region: '', tz: 'Africa/Casablanca', aliases: 'rak,marrakech' },
  { id: 'fej', name: 'Fes', country: 'Morocco', region: '', tz: 'Africa/Casablanca', aliases: 'fez,fes' },
  { id: 'hrg', name: 'Hurghada', country: 'Egypt', region: '', tz: 'Africa/Cairo', aliases: 'hrg' },
  { id: 'luxor', name: 'Luxor', country: 'Egypt', region: '', tz: 'Africa/Cairo', aliases: 'lxr,luxor' },
  { id: 'aqj', name: 'Aqaba', country: 'Jordan', region: '', tz: 'Asia/Amman', aliases: 'aqj' },
  { id: 'eth', name: 'Eilat', country: 'Israel', region: '', tz: 'Asia/Jerusalem', aliases: 'eth,eilat' },
  { id: 'hfa', name: 'Haifa', country: 'Israel', region: '', tz: 'Asia/Jerusalem', aliases: 'hfa' },
];
